version: 2

models:
  - name: fact_flight
    columns:
      - name: flightid
        tests:
          - not_null
          - unique
          - greater_than_zero
      - name: arrival
        tests:
          - not_null
      - name: airlineid
        tests:
          - relationships:
              to: ref('dim_airline')
              field: airlineid