version: 2

models:
  - name: fact_flight
    columns:
      - name: flightid
        data_tests:
          - not_null
          - unique
          - greater_than_zero
      - name: arrival
        data_tests:
          - not_null
      - name: airlineid
        data_tests:
          - relationships:
              to: ref('dim_airline')
              field: airlineid
