version: '3'

services:
  pg_host:
    container_name: postgres_db
    image: postgres:15
    ports:
      - 5435:5432
    expose:
      - 5432
    # volumes:
    #   - ./postgres/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgre_admin
      POSTGRES_PASSWORD: postgre_pwd
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    restart: always
